//
// Created by manu on 6/11/23.
//

#ifndef PROYECTO1_ARQUITECTURA_PROGARGS_HPP
#define PROYECTO1_ARQUITECTURA_PROGARGS_HPP

const float MULTIPLICADOR_DE_RADIO = 1.695;
const float DENSIDAD_DE_FLUIDO = 1000;
const float PRESION_DE_RIGIDEZ = 3;
const float COLISIONES_DE_RIGIDEZ = 30000;
const float AMORTIGUAMIENTO = 128;
const float VISCOSIDAD = 0.4;
const float TAMAÑO_DE_PARTICULA = 0.0002;
const float PASO_DE_TIEMPO = 0.001;


#endif //PROYECTO1_ARQUITECTURA_PROGARGS_HPP
